services:
#    wt_platform.example:
#        class: WT\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]


    oc_platform.antispam:
        class: WT\PlatformBundle\Antispam\WTAntispam
        arguments:
            - "@mailer"
            - %locale%
            - 50