<?php

namespace WT\PlatformBundle\Repository;
use Doctrine\ORM\QueryBuilder;


/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{

	public function findByDate($date)
{
    return $this->createQueryBuilder('a')
        ->andWhere('a.date BETWEEN :start AND :end')
        ->setParameter('start', new \Datetime(date('Y').'-01-01'))
        ->setParameter('end', new \Datetime(date('Y').'-01-31'))
        ->getQuery()
        ->getArrayResult()
    ;
    
}


}
