<?php

namespace WT\PlatformBundle\Repository;

/**
 * LettreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LettreRepository extends \Doctrine\ORM\EntityRepository
{
}
